var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/community/park/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__8f67c6d4._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_c2dd6a93._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5b9cc3c3._.js")
R.c("server/chunks/ssr/node_modules_@opentelemetry_api_build_esm_9e986a62._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_42657993._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/[root-of-the-server]__5a7b9567._.js")
R.m(67228)
module.exports=R.m(67228).exports
